name: Issue Notifier

on:
  issues:
    types:
      - opened

jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@main

        - name: Get Info
          run: |
            sudo apt-get install jq -y &> /dev/null
            echo "ISSUE_TITLE=$(jq --raw-output .issue.title ${GITHUB_EVENT_PATH})" >> ${GITHUB_ENV}
            echo "ISSUE_URL=$(jq --raw-output .issue.html_url ${GITHUB_EVENT_PATH})" >>  ${GITHUB_ENV}

        - name: Notify in Telegram
          run: |
            TgNotify() {
              curl -s -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" -d chat_id="${{ secrets.PRIV_CHAT_ID }}" \
              -d parse_mode=Markdown \
              -d text="${1}" \
              -d disable_web_page_preview=true
            }
            
            TgNotify "
            # ISSUE
            *New Issue Opened at* [${{ github.repository }}](https://github.com/${{ github.repository }})
            *Title:* \`${ISSUE_TITLE}\`
            *User:* [${{ github.actor }}](https://github.com/${{ github.actor }})
            *Issue URL:* [Here](${ISSUE_URL})"
